- name: configure vm(s)
  hosts: "router"
  gather_facts: yes
  become: yes

  tasks:
    - name: "Run Firewall"
      import_role:
        name: fcastello.firewall
      tags: ["firewall"]

    - name: "Run DHCP"
      import_role:
        name: fcastello.dhcpd_docker
      tags: ["dhcp"]
