firewall_masquerade_interfaces:
  - "eth0" #Asuming this is the public network interface
firewall_allowed_tcp_ports:
  - "22"
firewall_whitelist:
  - 192.168.0.0/16
  - 10.0.0.0/8
  - 172.16.0.0/12

dhcpd_domain_name: home.local
dhcpd_global_dns_servers: "8.8.8.8, 1.1.1.1"
dhcpd_global_authoritative: yes
dhcpd_bind_interface: eth1 # Asuming this is the private network interface

networks:
  - net_address: 192.168.1.0
    netmask: 255.255.255.0
    range: "192.168.2.21 192.168.2.250"
    gateway: 192.168.1.1
    domain_search: '"home.local", "example.com"'

static_hosts:
  - name: myhost
    ip: 192.168.1.3
    mac: ab:cd:ef:01:02:03